#!/bin/bash
# create_env.sh — Creates a new isolated sandbox environment
# Usage: ./create_env.sh <name> [ttl_seconds]

set -e

# ── Arguments ─────────────────────────────────────────────────────────────────
ENV_NAME="${1:-myapp}"
TTL="${2:-1800}"  # Default 30 minutes

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
ENVS_DIR="$BASE_DIR/envs"
LOGS_DIR="$BASE_DIR/logs"
NGINX_CONF_DIR="$BASE_DIR/nginx/conf.d"

# ── Generate unique environment ID ────────────────────────────────────────────
ENV_ID="env-$(cat /proc/sys/kernel/random/uuid | tr -d '-' | head -c 8)"
CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EXPIRES_AT=$(date -u -d "+${TTL} seconds" +"%Y-%m-%dT%H:%M:%SZ")

# ── Assign a random available port ────────────────────────────────────────────
APP_PORT=$(shuf -i 32000-33000 -n 1)

# Make sure port is not in use
while ss -tuln | grep -q ":$APP_PORT "; do
    APP_PORT=$(shuf -i 32000-33000 -n 1)
done

NETWORK_NAME="sandbox-net-$ENV_ID"
CONTAINER_NAME="sandbox-app-$ENV_ID"

echo "🚀 Creating environment: $ENV_NAME ($ENV_ID)"
echo "   TTL: ${TTL}s | Expires: $EXPIRES_AT"

# ── Create log directory ───────────────────────────────────────────────────────
mkdir -p "$LOGS_DIR/$ENV_ID"

# ── Create Docker network ──────────────────────────────────────────────────────
echo "🌐 Creating Docker network: $NETWORK_NAME"
docker network create "$NETWORK_NAME" > /dev/null

# ── Start app container ────────────────────────────────────────────────────────
echo "📦 Starting app container..."
docker run -d \
    --name "$CONTAINER_NAME" \
    --network "$NETWORK_NAME" \
    --label "sandbox.env=$ENV_ID" \
    --label "sandbox.name=$ENV_NAME" \
    -e ENV_ID="$ENV_ID" \
    -e ENV_NAME="$ENV_NAME" \
    -e APP_PORT="5000" \
    -p "$APP_PORT:5000" \
    sandbox-app:latest > /dev/null

# ── Start log shipping ─────────────────────────────────────────────────────────
echo "📝 Starting log shipping..."
docker logs -f "$CONTAINER_NAME" >> "$LOGS_DIR/$ENV_ID/app.log" 2>&1 &
LOG_PID=$!
echo "$LOG_PID" > "$LOGS_DIR/$ENV_ID/log_ship.pid"

# ── Write Nginx config ─────────────────────────────────────────────────────────
echo "🔧 Registering Nginx route..."
cat > "$NGINX_CONF_DIR/$ENV_ID.conf" << NGINX_EOF
# Auto-generated by create_env.sh for $ENV_ID
upstream $ENV_ID {
    server 127.0.0.1:$APP_PORT;
}

location /$ENV_ID/ {
    proxy_pass http://$ENV_ID/;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Env-ID $ENV_ID;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
}
NGINX_EOF

# ── Reload Nginx ───────────────────────────────────────────────────────────────
docker exec sandbox-nginx nginx -s reload 2>/dev/null || true

# ── Write state file (atomic) ──────────────────────────────────────────────────
echo "💾 Writing state file..."
TEMP_FILE=$(mktemp)
cat > "$TEMP_FILE" << STATE_EOF
{
    "id": "$ENV_ID",
    "name": "$ENV_NAME",
    "created_at": "$CREATED_AT",
    "expires_at": "$EXPIRES_AT",
    "ttl": $TTL,
    "status": "running",
    "port": $APP_PORT,
    "container": "$CONTAINER_NAME",
    "network": "$NETWORK_NAME",
    "log_pid": $LOG_PID
}
STATE_EOF
mv "$TEMP_FILE" "$ENVS_DIR/$ENV_ID.json"

# ── Print summary ──────────────────────────────────────────────────────────────
echo ""
echo "✅ Environment created successfully!"
echo "   ID:      $ENV_ID"
echo "   Name:    $ENV_NAME"
echo "   URL:     http://75.101.201.134/$ENV_ID/"
echo "   Direct:  http://75.101.201.134:$APP_PORT"
echo "   TTL:     ${TTL}s (expires $EXPIRES_AT)"
echo ""
